### ISSUE TITLE
[TESTING] Result for a little bit complicated mesh

### ISSUE THREAD

**Issue by MrForExample** [sairajk/easi-tex#2]
As expected, since this texture generation pipeline has no way to ensure consistent texture generation across the different views, and it doesn't try to keep the lighting condition the same across the different views, so the result is rather messy and unusable:

https://github.com/sairajk/easi-tex/assets/62230687/07b341b9-a8d8-4d52-9c2d-fff0abcc0071

Last year, I tried the similar workflow, but in addition to Canny ControlNet & IP-Adaptor, I used AnimateDiff as a mean to ensure consistent texture generation across the different views, and use [Brightness ControlNet](https://huggingface.co/latentcat/control_v1p_sd15_brightness) to keep the lighting condition the same across the different views.

Result is better but still takes long to generate & same parameters are not always gives good results.

https://github.com/sairajk/easi-tex/assets/62230687/e0fa5f21-b679-46bc-a84c-67bc2eb6a821

**Comment by sairajk** [comment]
Interesting, thank you for sharing.

**Comment by bdcms1** [comment]
@MrForExample Super awesome work, can you please share how to use AnimateDiff to eliminate the texture consistency issue?

**Comment by MrForExample** [comment]
@bdcms1 Actually, I'll release an opensource multi view texture gen system soon, it only takes 1-2 minutes to generate full-body texture for given mesh
