### ISSUE TITLE
TypeError: CrossAttention.__init__() got an unexpected keyword argument 'ip_adapter_use_tokens'

### ISSUE THREAD

**Issue by gaoxiangjun** [sairajk/easi-tex#3]
easi-tex/models/ControlNet/ldm/modules/attention.py", line 302, in __init__
    self.attn1 = attn_cls(query_dim=dim, heads=n_heads, dim_head=d_head, dropout=dropout,
TypeError: CrossAttention.__init__() got an unexpected keyword argument 'ip_adapter_use_tokens'

**Comment by sairajk** [comment]
Looks like you have not installed the `xformers` library.

**Comment by gaoxiangjun** [comment]
I got it! Thanks!
